# Generated by Django 5.2.8 on 2025-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Smartphone', 'Smartphone'), ('TV Smart', 'TV Smart')], default='Smartphone', max_length=15),
        ),
    ]
