# Generated by Django 5.2.8 on 2025-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='conectividade',
            field=models.CharField(max_length=120),
        ),
    ]
